indent_style = "Block"
reorder_imports = true
brace_style = "SameLineWhere"
wrap_comments = true
comment_width = 40
condense_wildcard_suffixes = true
edition = "2024"
empty_item_single_line = false
fn_single_line = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
import_layout = "HorizontalVertical"
match_block_trailing_comma = true
max_width = 80
imports_granularity = "Item"
reorder_impl_items = true